### ISSUE TITLE
potentially missing retry logic when waiting for resources

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-openstack-cpi-release#131]
seems like cpi hit " read timeout reached" error when waiting for server to be deleted. do we have some retry logic around this?

```
Rescued Bosh::Clouds::CloudError: Wait for server deletion: read timeout reached. backtrace: /var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb:34:in `fail_on_error'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:1056:in `destroy_server'
```

full stracktrace

```
E, [2018-04-22T08:41:59.637569 #10132] ERROR -- : Wait for server deletion: read timeout reached (Excon::Error::Timeout)
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.59.0/lib/excon/socket.rb:267:in `select_with_timeout'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.59.0/lib/excon/socket.rb:49:in `rescue in readline'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.59.0/lib/excon/socket.rb:45:in `readline'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.59.0/lib/excon/response.rb:63:in `parse'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:389:in `response'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:253:in `request'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:81:in `request'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-openstack-0.1.22/lib/fog/openstack/core.rb:81:in `request'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-openstack-0.1.22/lib/fog/compute/openstack/requests/get_server_details.rb:6:in `get_server_details'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-openstack-0.1.22/lib/fog/compute/openstack/models/servers.rb:50:in `get'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/core/model.rb:48:in `reload'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-openstack-0.1.22/lib/fog/compute/openstack/models/server.rb:118:in `reload'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:209:in `block (2 levels) in wait_resource'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:45:in `with_openstack'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:209:in `block in wait_resource'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:197:in `loop'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:197:in `wait_resource'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:1057:in `block in destroy_server'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb:42:in `catch_error'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:1057:in `destroy_server'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:322:in `block in delete_vm'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:316:in `delete_vm'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.3.0/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.3.0/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_openstack_cpi/bin/openstack_cpi:21:in `block in <top (required)>'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
/var/vcap/packages/bosh_openstack_cpi/bin/openstack_cpi:17:in `<top (required)>'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/var/vcap/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/var/vcap/packages/ruby_openstack_cpi/bin/bundle:23:in `load'
/var/vcap/packages/ruby_openstack_cpi/bin/bundle:23:in `<main>'
```

**Comment by beyhan** [comment]
Hi @cppforlife,

We don't have a retry logic for `Excon::Error::Timeout` errors in `destroy_server`. It seems to be the same also for `create_vm`. See this test case: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/8b3650629905f32767bcd0d1825c447aabdb458d/src/bosh_openstack_cpi/spec/unit/create_vm_spec.rb#L447. Is this differently handled by the other CPIs?

**Comment by voelzmo** [comment]
story: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/issues/131

**Comment by voelzmo** [comment]
Fixed by v40 of the CPI
